name: Deploy para WSL

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3


      - name: Configurar SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh  # Cria o diretório se não existir
          chmod 700 ~/.ssh  # Define a permissão correta
          
          echo -e "${SSH_PRIVATE_KEY//'\n'/$'\n'}" > ~/.ssh/id_rsa  # Salva a chave corretamente
          chmod 600 ~/.ssh/id_rsa  # Permissões corretas para a chave privada
          
          ssh-keyscan -p $WSL_PORT -H $WSL_HOST >> ~/.ssh/known_hosts
          
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa


      - name: Verificar chave SSH
        run: |
          ls -lah ~/.ssh
          cat ~/.ssh/id_rsa | head -n 5  # Exibe parte da chave para confirmar


      - name: Testar conexão SSH
        env:
          WSL_USER: "deploy"
          WSL_HOST: "0.tcp.sa.ngrok.io"
          WSL_PORT: "11683"
        run: |
          ssh -v -p $WSL_PORT -o StrictHostKeyChecking=no $WSL_USER@$WSL_HOST "echo 'Conexão SSH bem-sucedida'"


      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          WSL_USER: "deploy"
          WSL_HOST: "0.tcp.sa.ngrok.io"
          WSL_PORT: "11683"
        run: |
          ssh -o StrictHostKeyChecking=no -p $WSL_PORT $WSL_USER@$WSL_HOST << 'EOF'
            cd ~/tcc/plataforma-desenvolve-turismo
            git pull origin main
            cd ~/tcc/plataforma-desenvolve-turismo/app/forms/front
            pnpm add curl
            cd ~/tcc/plataforma-desenvolve-turismo/app/forms/api
            composer install
            composer dump-autoload
            sudo systemctl restart nginx 
          EOF
